development:
  clients:
    default:
      database: projects_test_development
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
test:
  clients:
    default:
      database: projects_test_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
